
(function(angular) {
    'use strict';

    // Need to be localized especially for Japan case, they don't want to use 'POOR'. Alternative should be 'NOT GOOD' which will impact HTML codes of index.html
    angular.module('ngMobileSpeedOne')
        .constant('RESOURCE', {
                    'APP_TITLE'                         : "Mobile Site Speed One Pager Generator",
                    'HEADER_PAGE_TITLE_EN'              : "Mobile Website Performance Report",
                    'HEADER_REPORT_TITLE_EN'            : "NOT YET DETERMINED'",
                    'SECTION_1_EN'                      : 'How fast is your Mobile Website ?',
                    'SECTION_2_EN'                      : 'How are your competitors performing?',
                    'SECTION_3_EN'                      : 'PageSpeed Insights',
                    'S1_MOBILE_SPEED_INDEX_EN'          : 'MOBILE PAGE SPEED INDEX',
                    'S1_WPT_SPEED_INDEX_EN'             : 'WPT SPEED INDEX',
                    'S1_VISUALLY_COMPLETE_TIME_EN'      : 'VISUALLY LOADED TIME',
                    'S1_VISUALLY_COMPLETE_EN'           : 'VISUALLY COMPLETE',
                    'S1_LOAD_TIME_EN'                   : 'LOAD TIME',
                    'S1_FULLY_LOADED_TIME_EN'           : 'FULLY LOADED TIME',
                    'S3_FIRST_IMPRESS_MATTER_EN'        : 'First Impression Matters',
                    'S3_P1_ATF_EN'                      : 'Prioritize visible content',
                    'S3_P1_RENDER_BLOCKING_EN'          : 'Eliminate render-blocking Javascript and CSS in above-the-fold content',
                    'S3_LIMIT_SERVER_HITS_EN'           : 'Limit Server Hits',
                    'S3_P2_SERVER_RESPONSE_TIME_EN'     : 'Reduce server response time',
                    'S3_P2_IMAGE_EN'                    : 'Optimize images',
                    'S3_P2_BROWSER_CACHING_EN'          : 'Leverage browser caching',
                    'S3_P2_REDIRECTS_EN'                : 'Avoid landing page redirects',
                    'S3_OPT_CONTENT_DELIVERY_EN'        : 'Optimize Contents Delivery',
                    'S3_P3_MIN_HTML_EN'                 : 'Minify HTML',
                    'S3_P3_MIN_JS_EN'                   : 'Minify JavaScript',
                    'S3_P3_MIN_CSS_EN'                  : 'Minify CSS',
                    'S3_P3_ENABLE_COMPRESSION_EN'       : 'Enable compression',
                    'FOOTER_MESSAGE_EN'                 : 'More ideas & discussion? Reach out to your Google contact',
                    'FOOTER_MESSAGE_LONG_EN'            : 'This is a high-level summary of the performance of your website. For a much deeper and custom analysis and for additional technical support, please contact your gTech Mobile POC',
                    'LEGEND_PASSED_EN'                  : 'Passed',
                    'LEGEND_CONSIDER_FIX_EN'            : 'Consider fix',
                    'LEGEND_SHOULD_FIX_EN'              : 'Should fix',
                    'GOOD_EN'                           : 'GOOD',
                    'FAIR_EN'                           : 'FAIR',
                    'POOR_EN'                           : 'POOR',
                    'UNKNOWN_EN'                         : 'UNKNOWN',
                    'GOOD_JA'                           : '速いです',
                    'FAIR_JA'                           : 'そこそこ速い',
                    'POOR_JA'                           : '遅いです',
                    'UNKNOWN_JA'                         : '判定不明',
                    'PROGRESS_TITLE_EN'                 : 'Analyzing Mobile Web Site',
                    'PROGRESS_SUB_TITLE_EN'             : 'Mobile Web site performance analysis just started.',
                    'PROGRESS_DESCRIPTION_EN'           : "We are analyzing your client's mobile website by calling Page Speed Insight API and WPT(Webpagetest) API. Once the API is successfully called and the data is ready, we are comparing them with your client's competitors' speed index. With those two steps of analysis, we are providing insights on where they stand among their competitors and what action they should take to improve their webpage performance.",
                    'PROGRESS_CONTACT_EN'               : "This is a summary of your client's mobile website performance, which is designed to support your initial pitch. If your client shows interest in their site performance improvement and the provided recommendation, please reach out to your gTech contact.",
                    'PROGRESS_SUGGESTION_EN'            : "If you can't find 'Validating user input data - Succeeded'. Please go back to the previous page and do user input again. Please keep this in mind that you should not block cookie in your broser. If you see 'Retrieving Web Page Test Index data - Failed', please refresh this page again as it could be temporary issue. But if you see the error continuously, please contact your gTech POC with your error message. Or if you see 'Calling Page Speed Insight API - Failed', please check if URL input you did in the previous page is correct URL by typing them in new tab and checking if the site is valid one.",
                    'PROGRESS_SUGGESTION_HEADER_EN'     : 'Ah, We encountered error !',
                    'PROGRESS_SUGGESTION_USER_INPUT_EN' : "If you can't find 'Validating user input data - Succeeded'. Please go back to the previous page and do user input again. Please keep this in mind that you should not block cookie in your broser.",
                    'PROGRESS_SUGGESTION_WPT_EN'        : "If you see 'Retrieving Web Page Test Index data - Failed', please refresh this page again as it could be temporary issue. Or Open new tab and hit moma/ so that you have right credential on your session",
                    'PROGRESS_SUGGESTION_API_EN'        : "If you see 'Calling Page Speed Insight API - Failed', please check if URL input you did in the previous page is correct URL by typing them in new tab and checking if the site is valid one.",
                    'PROGRESS_SUGGESTION_CONTACT_EN'    : "Please contact to your gTech POC or mincheoulkim@google.com in continous error occurance.",
                    'PROGRESS_USER_INPUT_EN'            : 'Validating user input data - ',
                    'PROGRESS_WPT_EN'                   : 'Retrieving Web Page Test Index data - ',
                    'PROGRESS_API_EN'                   : 'Calling Page Speed Insight API - ',
                    'PROGRESS_WPT_API_EN'               : 'Calling WebPageTest API - ',
                    'USER_INPUT_FAIL_SUGGESTION_EN'                 : "Failed to retrieve data. Please open new tab and hit 'moma/' and retry. Or contact your gTech POC.",
                    'ACCESS_PERMISSIN_DENIED_SUGGESTION_EN'         : "Not authorized to access necessary resources. Please join dremel-users, and jagr-xxx via go/jagr-access",
                    'INTERNAL_ERR_MSG_USER_INPUT_MARKET_FAILED'     : "FAILED - WELCOME.HTML : angular.element.ready - dremelF.executeSQL(Market)",
                    'INTERNAL_ERR_MSG_USER_INPUT_PERMISSION_DENIED' : "FAILED - WELCOME.HTML : angular.element.ready - PERMISSION DENIED",
                    'INTERNAL_ERR_MSG_USER_INPUT_MARKET_SUCCEED'    : "SUCCEED - WELCOME.HTML : angular.element.ready - dremelF.executeSQL(Market)",
                    'INTERNAL_ERR_MSG_ADVERTISER_FAILED'            : "FAILED - WELCOME.HTML : $scope.getMarkets - dremelF.executeSQL(Advertisers)",
                    'INTERNAL_ERR_MSG_ADVERTISER_SUCCEEDED'         : "SUCCEED - WELCOME.HTML : $scope.getMarkets - dremelF.executeSQL(Advertisers)",
                    'INTERNAL_ERR_MSG_VERTICAL_FAILED'              : "FAILED - WELCOME.HTML : $scope.getMarkets - dremelF.executeSQL(Verticals)",
                    'INTERNAL_ERR_MSG_VERTICAL_SUCCEEDED'           : "SUCCEED - WELCOME.HTML : $scope.getMarkets - dremelF.executeSQL(Verticals)",
                    'INTERNAL_ERR_MSG_WPT_SUCCEEDED'                : "SUCCEED - INDEX.HTML : angular.element.ready - dremelF.executeSQL(WPTIndex)",
                    'INTERNAL_ERR_MSG_WPT_FAILED'                   : "FAILED - INDEX.HTML : angular.element.ready - dremelF.executeSQL(WPTIndex)",
                    'INTERNAL_ERR_MSG_COOKIE_SUCCEEDED'             : "SUCCEED - INDEX.HTML : angular.element.ready - retrieveUserInputData(cookie)",
                    'INTERNAL_ERR_MSG_API_SUCCEEDED'                : "SUCCEED - INDEX.HTML : angular.element.ready - retrievePageSpeedInsightDat(API)",
                    'INTERNAL_ERR_MSG_API_FAILED'                   : "FAILED - INDEX.HTML : angular.element.ready - retrievePageSpeedInsightDat(API)"
        })
})(window.angular);
